# Generated by Django 4.1.1 on 2022-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_motherboard_price_processor_price_ram_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название кулера', max_length=100, verbose_name='Название кулера')),
                ('power', models.IntegerField(help_text='Введите рассеиваемую мощность', verbose_name='Рассеиваемая мощность')),
                ('price', models.FloatField(default=0, help_text='Введите цену', verbose_name='цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='Coolers/', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='processor',
            name='tdp',
            field=models.IntegerField(default=0, help_text='Введите тепловыделение процессора (TDP)', verbose_name='Тепловыделение (TDP)'),
        ),
    ]
