# Generated by Django 4.1.1 on 2022-10-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_videocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='price',
            field=models.FloatField(default=0, help_text='Введите цену', verbose_name='цена'),
        ),
    ]
