# Generated by Django 4.1.1 on 2022-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_videocard_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power_block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название блока питания', max_length=100, verbose_name='Название блока питания')),
                ('power', models.FloatField(default=0, help_text='Введите мощность в Вт', verbose_name='Мощность')),
                ('price', models.FloatField(default=0, help_text='Введите цену', verbose_name='цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='Power_blocks/', verbose_name='Изображение')),
            ],
        ),
    ]
