# Generated by Django 4.1.1 on 2022-10-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_power_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSD_M2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название SSD M.2', max_length=100, verbose_name='Название SSD M.2')),
                ('capacity', models.FloatField(help_text='Введите объём памяти в Гб', verbose_name='Объём памяти')),
                ('price', models.FloatField(default=0, help_text='Введите цену', verbose_name='цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='Power_blocks/', verbose_name='Изображение')),
            ],
        ),
        migrations.AddField(
            model_name='motherboard',
            name='m2_slots',
            field=models.FloatField(default=0, help_text='Введите кол-во разьемов М.2', verbose_name='Разьемы М.2'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='sata_slots',
            field=models.FloatField(default=0, help_text='Введите кол-во разьемов SATA', verbose_name='Разьемы SATA'),
        ),
    ]
