# Generated by Django 4.1.1 on 2022-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_ssd_m2_motherboard_m2_slots_motherboard_sata_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='m2_slots',
            field=models.IntegerField(default=0, help_text='Введите кол-во разьемов М.2', verbose_name='Разьемы М.2'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='sata_slots',
            field=models.IntegerField(default=0, help_text='Введите кол-во разьемов SATA', verbose_name='Разьемы SATA'),
        ),
    ]
