# Generated by Django 4.1.1 on 2022-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_motherboard_m2_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название жесткого диска (HDD)', max_length=100, verbose_name='Название жесткого диска (HDD)')),
                ('capacity', models.FloatField(help_text='Введите объём памяти в Гб', verbose_name='Объём памяти')),
                ('price', models.FloatField(default=0, help_text='Введите цену', verbose_name='цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='Power_blocks/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='SSD_sata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название SSD Sata', max_length=100, verbose_name='Название SSD Sata')),
                ('capacity', models.FloatField(help_text='Введите объём памяти в Гб', verbose_name='Объём памяти')),
                ('price', models.FloatField(default=0, help_text='Введите цену', verbose_name='цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='Power_blocks/', verbose_name='Изображение')),
            ],
        ),
    ]
