# Generated by Django 4.1.1 on 2022-10-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_hdd_ssd_sata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='hdd/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ssd_m2',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='ssd_m2/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ssd_sata',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='ssd_sata/', verbose_name='Изображение'),
        ),
    ]
