# Generated by Django 4.1.1 on 2022-10-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_hdd_image_alter_ssd_m2_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите полное название SSD Sata', max_length=100, verbose_name='Название SSD Sata')),
                ('form', models.CharField(blank=True, help_text='Введите форм-фактор корпуса', max_length=25, null=True, verbose_name='Форм-фактор')),
                ('price', models.FloatField(default=0, help_text='Введите цену', verbose_name='цена')),
                ('image', models.ImageField(blank=True, help_text='Загрузите одно изображение', null=True, upload_to='corpuses/', verbose_name='Изображение')),
            ],
        ),
    ]
