# Generated by Django 4.1.2 on 2022-11-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_cooler_review_alter_corpus_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooler',
            options={'verbose_name': 'Кулер', 'verbose_name_plural': 'Кулеры'},
        ),
        migrations.AlterModelOptions(
            name='corpus',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='hdd',
            options={'verbose_name': 'Жесткий диск', 'verbose_name_plural': 'Жесткие диски'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История заказов', 'verbose_name_plural': 'История заказов'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
        migrations.AlterModelOptions(
            name='power_block',
            options={'verbose_name': 'Блок питания', 'verbose_name_plural': 'Блоки питания'},
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': 'Оперативная память', 'verbose_name_plural': 'Оперативная память'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='ssd_m2',
            options={'verbose_name': 'Твердотельный накопитель М.2', 'verbose_name_plural': 'Твердотельные накопители М.2'},
        ),
        migrations.AlterModelOptions(
            name='ssd_sata',
            options={'verbose_name': 'Твердотельный накопитель SATA', 'verbose_name_plural': 'Твердотельные накопители SATA'},
        ),
        migrations.AlterModelOptions(
            name='videocard',
            options={'verbose_name': 'Видеокарта', 'verbose_name_plural': 'Видеокарты'},
        ),
        migrations.AlterField(
            model_name='cooler',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='power_block',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='processor',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='ssd_m2',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='ssd_sata',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='review',
            field=models.ManyToManyField(blank=True, to='mainapp.review', verbose_name='Отзывы'),
        ),
    ]
